-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 16:59:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_locadora` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_locadora` ;

-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_atividade` (
  `cod_atividade` INT(11) NOT NULL AUTO_INCREMENT,
  `atividade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_atividade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_estado` (
  `cod_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_ator` (
  `cod_ator` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_ator` VARCHAR(100) NOT NULL,
  `nome_completo_ator` VARCHAR(200) NOT NULL,
  `imagem_ator` TEXT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cod_estado` INT(11) NOT NULL,
  PRIMARY KEY (`cod_ator`),
  INDEX `fk_tbl_ator_tbl_estado1_idx` (`cod_estado` ASC),
  CONSTRAINT `fk_tbl_ator_tbl_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `db_locadora`.`tbl_estado` (`cod_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_atividade_ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_atividade_ator` (
  `cod_atividade_ator` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_ator` INT(11) NOT NULL,
  `cod_atividade` INT(11) NOT NULL,
  PRIMARY KEY (`cod_atividade_ator`),
  INDEX `fk_tbl_atividade_ator_tbl_ator1_idx` (`cod_ator` ASC),
  INDEX `fk_tbl_atividade_ator_tbl_atividade1_idx` (`cod_atividade` ASC),
  CONSTRAINT `fk_tbl_atividade_ator_tbl_atividade1`
    FOREIGN KEY (`cod_atividade`)
    REFERENCES `db_locadora`.`tbl_atividade` (`cod_atividade`),
  CONSTRAINT `fk_tbl_atividade_ator_tbl_ator1`
    FOREIGN KEY (`cod_ator`)
    REFERENCES `db_locadora`.`tbl_ator` (`cod_ator`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_cidade` (
  `cod_cidade` INT(11) NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(100) NOT NULL,
  `cod_estado` INT(11) NOT NULL,
  PRIMARY KEY (`cod_cidade`),
  INDEX `cod_estado` (`cod_estado` ASC),
  CONSTRAINT `tbl_cidade_ibfk_1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `db_locadora`.`tbl_estado` (`cod_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_diretor` (
  `cod_diretor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_diretor` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cod_diretor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_loja` (
  `cod_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `endereco_mapa` TEXT NOT NULL,
  `cod_cidade` INT(11) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`cod_endereco`),
  INDEX `cod_cidade` (`cod_cidade` ASC),
  CONSTRAINT `tbl_endereco_ibfk_1`
    FOREIGN KEY (`cod_cidade`)
    REFERENCES `db_locadora`.`tbl_cidade` (`cod_cidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_faleconosco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_faleconosco` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `profissao` VARCHAR(100) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `telefone` VARCHAR(100) NULL DEFAULT NULL,
  `celular` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `facebook` TEXT NULL DEFAULT NULL,
  `home_page` TEXT NULL DEFAULT NULL,
  `info_produtos` TEXT NULL DEFAULT NULL,
  `sugestao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_pais` (
  `cod_pais` INT(11) NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_filme` (
  ` cod_filme` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_filme` VARCHAR(200) NOT NULL,
  `imagem_filme` TEXT NOT NULL,
  `cod_pais` INT(11) NOT NULL,
  `duracao_filme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (` cod_filme`),
  INDEX `fk_tbl_filme_tbl_pais1_idx` (`cod_pais` ASC),
  CONSTRAINT `fk_tbl_filme_tbl_pais1`
    FOREIGN KEY (`cod_pais`)
    REFERENCES `db_locadora`.`tbl_pais` (`cod_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_filme_ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_filme_ator` (
  `cod_filme_ator` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_filme` INT(11) NOT NULL,
  `cod_ator` INT(11) NOT NULL,
  PRIMARY KEY (`cod_filme_ator`),
  INDEX `fk_tbl_filme_ator_tbl_filme1_idx` (`cod_filme` ASC),
  INDEX `fk_tbl_filme_ator_tbl_ator1_idx` (`cod_ator` ASC),
  CONSTRAINT `fk_tbl_filme_ator_tbl_ator1`
    FOREIGN KEY (`cod_ator`)
    REFERENCES `db_locadora`.`tbl_ator` (`cod_ator`),
  CONSTRAINT `fk_tbl_filme_ator_tbl_filme1`
    FOREIGN KEY (`cod_filme`)
    REFERENCES `db_locadora`.`tbl_filme` (` cod_filme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_filme_diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_filme_diretor` (
  `cod_filme_diretor` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_diretor` INT(11) NOT NULL,
  `cod_filme` INT(11) NOT NULL,
  PRIMARY KEY (`cod_filme_diretor`),
  INDEX `fk_tbl_filme_diretor_tbl_diretor1_idx` (`cod_diretor` ASC),
  INDEX `fk_tbl_filme_diretor_tbl_filme1_idx` (`cod_filme` ASC),
  CONSTRAINT `fk_tbl_filme_diretor_tbl_diretor1`
    FOREIGN KEY (`cod_diretor`)
    REFERENCES `db_locadora`.`tbl_diretor` (`cod_diretor`),
  CONSTRAINT `fk_tbl_filme_diretor_tbl_filme1`
    FOREIGN KEY (`cod_filme`)
    REFERENCES `db_locadora`.`tbl_filme` (` cod_filme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_nivelusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_nivelusuario` (
  `cod_nivel` INT(11) NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`cod_nivel`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_locadora`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locadora`.`tbl_usuario` (
  `cod_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(200) NOT NULL,
  `email_usuario` VARCHAR(250) NOT NULL,
  `senha_usuario` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '0',
  `cod_nivel` INT(11) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  INDEX `fk_usuario_nivel` (`cod_nivel` ASC),
  CONSTRAINT `fk_usuario_nivel`
    FOREIGN KEY (`cod_nivel`)
    REFERENCES `db_locadora`.`tbl_nivelusuario` (`cod_nivel`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
